#!/usr/bin/env python3
"""Re-stagger PUBLISH_DATES in seo_inject.py for a batch of pages.

Why: a content batch that ships on one calendar day leaves 30-50 pages sharing a
single `datePublished`, which reads as a mass-publish dump. Spreading those dates
backwards over a window makes the rollout look like a natural multi-day cadence.

This edits ONE source of truth -- the `PUBLISH_DATES` dict in `seo_inject.py`.
The per-page meta tags / JSON-LD are regenerated by re-running `python seo_inject.py`
(and, with the lastmod change, `sitemap.xml` follows the same dates).

Usage
-----
    python scripts/restagger-publish-dates.py \
        --match 2026-09-29 --start 2026-09-15 --end 2026-09-29 [--seed N] [--dry-run]

    --match   current date to select the batch (exact string match)
    --start   first day of the target window (inclusive)
    --end     last  day of the target window (inclusive)
    --seed    RNG seed; omit for a random one (printed so the run is reproducible)
    --max-per-day  cap on how many pages may share one day (default: unlimited)
    --dry-run print the plan, change nothing
    --out     also dump the mapping as JSON to this path (optional)

Guarantees
----------
* Every selected page must exist on disk, or the run aborts before writing.
* Each replacement is asserted to match exactly once, or the run aborts.
* `--end` must not be later than `--match`, so this only ever moves dates BACK.
"""
import argparse
import json
import os
import random
import re
import secrets
import sys
from datetime import date, timedelta

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SEO = os.path.join(ROOT, "seo_inject.py")

BANK_START = "PUBLISH_DATES = {"
BANK_END = "# Segment -> nice breadcrumb name"


def load_bank(src):
    i = src.index(BANK_START)
    j = src.index(BANK_END)
    return i, j, src[i:j]


def parse_entries(block):
    return re.findall(r'"([^"]+)": "(\d{4}-\d{2}-\d{2})"', block)


def daterange(start, end):
    d = start
    while d <= end:
        yield d
        d += timedelta(days=1)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--match", required=True, help="current date to select (YYYY-MM-DD)")
    ap.add_argument("--start", required=True, help="window start (YYYY-MM-DD)")
    ap.add_argument("--end", required=True, help="window end (YYYY-MM-DD)")
    ap.add_argument("--seed", type=int, default=None)
    ap.add_argument("--max-per-day", type=int, default=0,
                    help="cap pages per day (0 = unlimited); rejection-sampled so the "
                         "draw stays uniform, just conditioned on the cap")
    ap.add_argument("--dry-run", action="store_true")
    ap.add_argument("--out", default=None)
    a = ap.parse_args()

    match = date.fromisoformat(a.match)
    start = date.fromisoformat(a.start)
    end = date.fromisoformat(a.end)

    if start > end:
        sys.exit("ABORT: --start is after --end")
    if end > match:
        sys.exit("ABORT: --end (%s) is later than --match (%s); this tool only moves dates back"
                 % (end, match))
    window = list(daterange(start, end))

    src = open(SEO, encoding="utf-8").read()
    i, j, block = load_bank(src)
    entries = parse_entries(block)
    if not entries:
        sys.exit("ABORT: could not parse any PUBLISH_DATES entries")

    targets = [p for p, d in entries if d == a.match]
    if not targets:
        sys.exit("ABORT: no PUBLISH_DATES entry currently dated %s" % a.match)

    # every target must exist and must have an entry that is unique in the block
    missing = [p for p in targets if not os.path.exists(os.path.join(ROOT, p))]
    if missing:
        sys.exit("ABORT: %d target page(s) missing on disk:\n  %s"
                 % (len(missing), "\n  ".join(missing)))
    for p in targets:
        if block.count('"%s":' % p) != 1:
            sys.exit("ABORT: %r is not uniquely keyed in PUBLISH_DATES" % p)

    seed = a.seed if a.seed is not None else secrets.randbelow(10 ** 9)
    rng = random.Random(seed)

    # fully independent uniform draw -> some days may be empty, some busy.
    # With --max-per-day we rejection-sample: every accepted draw is still a
    # uniform draw, merely conditioned on the cap, so the result stays a genuine
    # random assignment rather than a hand-balanced one.
    attempts = 0
    while True:
        attempts += 1
        draw = {p: rng.choice(window) for p in targets}
        if a.max_per_day <= 0:
            break
        counts = {}
        for v in draw.values():
            counts[v] = counts.get(v, 0) + 1
        if max(counts.values()) <= a.max_per_day:
            break
        if attempts >= 200000:
            sys.exit("ABORT: could not satisfy --max-per-day %d for %d pages in %d days "
                     "(capacity %d); widen the window or raise the cap"
                     % (a.max_per_day, len(targets), len(window), a.max_per_day * len(window)))
    mapping = {p: v.isoformat() for p, v in draw.items()}
    if a.max_per_day > 0:
        print("CAP: <=%d per day (accepted after %d rejection attempt(s))" % (a.max_per_day, attempts))

    hist = {d: 0 for d in window}
    for v in mapping.values():
        hist[date.fromisoformat(v)] += 1

    print("SEED: %d  (rerun with --seed %d to reproduce)" % (seed, seed))
    print("SELECTED: %d page(s) currently dated %s" % (len(targets), a.match))
    print("WINDOW:   %s .. %s  (%d days)" % (start, end, len(window)))
    print("\n%-62s %s" % ("PAGE", "NEW DATE"))
    for p in sorted(targets):
        print("%-62s %s" % (p, mapping[p]))

    print("\nDAY HISTOGRAM")
    for d in window:
        n = hist[d]
        print("  %s  %2d %s" % (d, n, "#" * n))
    empty = [str(d) for d in window if hist[d] == 0]
    print("\n  empty days: %s" % (", ".join(empty) if empty else "none"))
    print("  min/max per day: %d / %d" % (min(hist.values()), max(hist.values())))

    if a.out:
        with open(a.out, "w", encoding="utf-8") as fh:
            json.dump({"seed": seed, "match": a.match, "window": [str(start), str(end)],
                       "mapping": mapping}, fh, indent=2, sort_keys=True)
        print("\nwrote %s" % a.out)

    if a.dry_run:
        print("\nDRY RUN — seo_inject.py untouched.")
        return

    new_block = block
    for p, nd in mapping.items():
        old = '"%s": "%s"' % (p, a.match)
        new = '"%s": "%s"' % (p, nd)
        if new_block.count(old) != 1:
            sys.exit("ABORT: expected exactly 1 occurrence of %s, found %d"
                     % (old, new_block.count(old)))
        new_block = new_block.replace(old, new)

    # sanity: entry count and every other date must be untouched
    if len(parse_entries(new_block)) != len(entries):
        sys.exit("ABORT: entry count changed during rewrite")

    open(SEO, "w", encoding="utf-8", newline="").write(src[:i] + new_block + src[j:])
    print("\nwrote %s (%d dates re-staggered)" % (SEO, len(mapping)))
    print("Next: python seo_inject.py -> python scripts/build-content-index.py -> node scripts/build-llms-full.mjs")


if __name__ == "__main__":
    main()
