/**
 * curated-200.mjs — the hand-curated Top-200 intent set.
 *
 * Curation is editorial (cluster balance, funnel value, page-buildability for
 * MysticDo's existing production pipeline). The NUMBERS are not editorial: the
 * join script looks every entry up in library.json (measured Google Suggest
 * signal) and attaches nVariants / nQueries / crossSeeds / geo.
 *
 * `q`    = canonical intent phrasing (what the page H1 should answer)
 * `keys` = substrings used to find the measured evidence in the raw pool
 * `type` = intent type   | `form` = recommended page archetype
 * `funnel` = D1 引流 / D2 培育 / D3 转化
 * `url`  = suggested clean-URL path on mysticdo.com
 */

export const CURATED = [
  /* ============ 1. LOVE & RELATIONSHIPS (30) ============ */
  ['does he love me', ['does he love me'], 'love_relationships', 'yes_no', '决策页', 'D2', '/questions/love-relationships/does-he-love-me'],
  ['does he still love me', ['does he still love me'], 'love_relationships', 'yes_no', '决策页', 'D2', '/questions/love-relationships/does-he-still-love-me'],
  ['does he miss me', ['does he miss me'], 'love_relationships', 'yes_no', '决策页', 'D2', '/questions/love-relationships/does-he-miss-me'],
  ['does he think about me', ['does he think about me'], 'love_relationships', 'yes_no', '决策页', 'D2', '/questions/love-relationships/does-he-think-about-me'],
  ['does he like me', ['does he like me'], 'love_relationships', 'yes_no', '决策页', 'D2', '/questions/love-relationships/does-he-like-me'],
  ['does my crush like me back', ['does my crush like me'], 'love_relationships', 'yes_no', '决策页', 'D2', '/questions/love-relationships/does-my-crush-like-me'],
  ['is he the one', ['is he the one'], 'love_relationships', 'yes_no', '决策页', 'D2', '/questions/love-relationships/is-he-the-one'],
  ['is he cheating', ['is he cheating'], 'love_relationships', 'yes_no', '决策页', 'D3', '/questions/love-relationships/is-he-cheating'],
  ['is he serious about me', ['is he serious about me'], 'love_relationships', 'yes_no', '决策页', 'D2', '/questions/love-relationships/is-he-serious-about-me'],
  ['is he dating someone else', ['is he dating someone else'], 'love_relationships', 'yes_no', '决策页', 'D2', '/questions/love-relationships/is-he-dating-someone-else'],
  ['does he regret losing me', ['does he regret losing me'], 'love_relationships', 'yes_no', '决策页', 'D2', '/questions/love-relationships/does-he-regret-losing-me'],
  ['does he want a relationship with me', ['does he want a relationship'], 'love_relationships', 'yes_no', '决策页', 'D2', '/questions/love-relationships/does-he-want-a-relationship'],
  ['will he come back', ['will he come back'], 'love_relationships', 'yes_no', '决策页', 'D2', '/questions/love-relationships/will-he-come-back'],
  ['will he come back after no contact', ['will he come back after no contact'], 'love_relationships', 'yes_no', '决策页', 'D2', '/questions/love-relationships/will-he-come-back-after-no-contact'],
  ['is my ex coming back', ['is my ex coming back'], 'love_relationships', 'yes_no', '决策页', 'D2', '/questions/love-relationships/is-my-ex-coming-back'],
  ['should i text him', ['should i text him'], 'love_relationships', 'yes_no', '决策页', 'D2', '/questions/love-relationships/should-i-text-him'],
  ['should i break up', ['should i break up'], 'love_relationships', 'yes_no', '决策页', 'D2', '/questions/love-relationships/should-i-break-up'],
  ['is my relationship toxic', ['is my relationship toxic'], 'love_relationships', 'yes_no', '决策页', 'D2', '/questions/love-relationships/is-my-relationship-toxic'],
  ['will my relationship last', ['will my relationship last'], 'love_relationships', 'yes_no', '决策页', 'D3', '/questions/love-relationships/will-my-relationship-last'],
  ['am i in love', ['am i in love'], 'love_relationships', 'yes_no', '决策页', 'D1', '/questions/love-relationships/am-i-in-love'],
  ['why is he distant all of a sudden', ['why is he distant'], 'love_relationships', 'wh', '决策页', 'D2', '/questions/love-relationships/why-is-he-distant'],
  ['why did he ghost me', ['why did he ghost'], 'love_relationships', 'wh', '决策页', 'D2', '/questions/love-relationships/why-did-he-ghost-me'],
  ['why do i keep thinking about him', ['keeps thinking about him', 'keep thinking about him', 'stop thinking about him'], 'love_relationships', 'wh', '决策页', 'D2', '/questions/love-relationships/why-cant-i-stop-thinking-about-him'],
  ['how to get over someone', ['how to get over someone', 'how to get over him'], 'love_relationships', 'how_to', '决策页', 'D2', '/questions/love-relationships/how-to-get-over-someone'],
  ['how to tell if he loves you', ['how to tell if he loves you'], 'love_relationships', 'how_to', '清单页', 'D1', '/questions/love-relationships/how-to-tell-if-he-loves-you'],
  ['signs he loves you', ['signs he loves you'], 'love_relationships', 'signs', '清单页', 'D1', '/questions/love-relationships/signs-he-loves-you'],
  ['am i going to be alone forever', ['alone forever', 'will i ever find love'], 'love_relationships', 'yes_no', '决策页', 'D2', '/questions/love-relationships/will-i-ever-find-love'],
  ['when will i get married', ['when will i get married'], 'love_relationships', 'wh', '工具页', 'D2', '/questions/love-relationships/when-will-i-get-married'],
  ['who will i marry', ['who will i marry'], 'love_relationships', 'wh', '决策页', 'D1', '/questions/love-relationships/who-will-i-marry'],
  ['am i in a karmic relationship', ['karmic relationship'], 'love_relationships', 'yes_no', '决策页', 'D2', '/questions/love-relationships/karmic-relationship-signs'],

  /* ============ 2. TWIN FLAME & SOULMATE (10) ============ */
  ['who is my soulmate', ['who is my soulmate'], 'twin_flame_soulmate', 'wh', '决策页', 'D2', '/questions/love-relationships/who-is-my-soulmate'],
  ['when will i meet my soulmate', ['when will i meet my soulmate'], 'twin_flame_soulmate', 'wh', '决策页', 'D2', '/questions/love-relationships/when-will-i-meet-my-soulmate'],
  ['how to know if someone is your soulmate', ['how to know if someone is your soulmate', 'how to know who is my soulmate'], 'twin_flame_soulmate', 'how_to', '决策页', 'D2', '/questions/love-relationships/how-to-know-your-soulmate'],
  ['twin flame vs soulmate', ['twin flame vs soulmate'], 'twin_flame_soulmate', 'wh', '概念页', 'D1', '/questions/love-relationships/twin-flame-vs-soulmate'],
  ['karmic vs twin flame', ['karmic vs twin flame'], 'twin_flame_soulmate', 'wh', '概念页', 'D1', '/questions/love-relationships/karmic-vs-twin-flame'],
  ['is he my twin flame', ['is he my twin flame'], 'twin_flame_soulmate', 'yes_no', '决策页', 'D2', '/questions/love-relationships/is-he-my-twin-flame'],
  ['signs he is my twin flame', ['signs he is my twin flame', 'signs he is my twin'], 'twin_flame_soulmate', 'signs', '清单页', 'D1', '/questions/love-relationships/twin-flame-signs'],
  ['twin flame separation meaning', ['twin flame separation'], 'twin_flame_soulmate', 'meaning', '概念页', 'D2', '/questions/love-relationships/twin-flame-separation'],
  ['twin flame reunion signs', ['twin flame reunion'], 'twin_flame_soulmate', 'signs', '概念页', 'D2', '/questions/love-relationships/twin-flame-reunion-signs'],
  ['twin flame stages', ['twin flame stages'], 'twin_flame_soulmate', 'wh', '概念页', 'D1', '/questions/love-relationships/twin-flame-stages'],

  /* ============ 3. DREAMS (14) ============ */
  ['what does it mean when you dream about someone', ['dream about someone'], 'dreams', 'meaning', '解读页', 'D1', '/questions/dreams/dream-about-someone'],
  ['what does it mean when you dream about your ex', ['dream about your ex'], 'dreams', 'meaning', '解读页', 'D1', '/questions/dreams/dream-about-your-ex'],
  ['why do i keep dreaming about the same person', ['keep dreaming about the same person', 'keep dreaming about someone', 'keep dreaming about my ex'], 'dreams', 'wh', '解读页', 'D1', '/questions/dreams/recurring-dream-about-someone'],
  ['dream about snakes meaning', ['dream about snakes', 'dream about snake'], 'dreams', 'meaning', '解读页', 'D1', '/questions/dreams/dream-about-snakes'],
  ['dream about spiders meaning', ['dream about spiders', 'dream about spider'], 'dreams', 'meaning', '解读页', 'D1', '/questions/dreams/dream-about-spiders'],
  ['dream about water meaning', ['dream about water'], 'dreams', 'meaning', '解读页', 'D1', '/questions/dreams/dream-about-water'],
  ['dream about falling teeth meaning', ['teeth falling', 'dream about falling teeth'], 'dreams', 'meaning', '解读页', 'D1', '/questions/dreams/dream-about-teeth-falling-out'],
  ['dream about being chased meaning', ['being chased'], 'dreams', 'meaning', '解读页', 'D1', '/questions/dreams/dream-about-being-chased'],
  ['dream about death meaning', ['dream about death'], 'dreams', 'meaning', '解读页', 'D1', '/questions/dreams/dream-about-death'],
  ['what does it mean when you dream about someone dying', ['dream about someone dying'], 'dreams', 'meaning', '解读页', 'D1', '/questions/dreams/dream-about-someone-dying'],
  ['dream about a deceased loved one', ['deceased', 'dream about my dead'], 'dreams', 'meaning', '解读页', 'D1', '/questions/dreams/dream-about-deceased-loved-one'],
  ['lucid dreaming how to', ['lucid dream'], 'dreams', 'how_to', '指南页', 'D1', '/guides/lucid-dreaming-beginners'],
  ['recurring dreams meaning', ['recurring dream'], 'dreams', 'meaning', '解读页', 'D1', '/questions/dreams/recurring-dreams'],
  ['can dreams predict the future', ['dreams predict the future', 'dream predict'], 'dreams', 'yes_no', '概念页', 'D1', '/questions/dreams/can-dreams-predict-the-future'],

  /* ============ 4. ANGEL NUMBERS & NUMEROLOGY (18) ============ */
  ['what does 1111 mean', ['does 1111 mean', 'does 1111'], 'angel_numbers', 'meaning', '解读页', 'D1', '/questions/angel-numbers/1111-meaning'],
  ['what does 222 mean', ['does 222 mean', 'does 222'], 'angel_numbers', 'meaning', '解读页', 'D1', '/questions/angel-numbers/222-meaning'],
  ['what does 333 mean', ['does 333 mean', 'does 333'], 'angel_numbers', 'meaning', '解读页', 'D1', '/questions/angel-numbers/333-meaning'],
  ['what does 444 mean', ['does 444 mean', 'does 444'], 'angel_numbers', 'meaning', '解读页', 'D1', '/questions/angel-numbers/444-meaning'],
  ['what does 555 mean', ['does 555 mean', 'does 555'], 'angel_numbers', 'meaning', '解读页', 'D1', '/questions/angel-numbers/555-meaning'],
  ['what does 777 mean', ['does 777 mean', 'does 777'], 'angel_numbers', 'meaning', '解读页', 'D1', '/questions/angel-numbers/777-meaning'],
  ['what does 888 mean', ['does 888 mean', 'does 888'], 'angel_numbers', 'meaning', '解读页', 'D1', '/questions/angel-numbers/888-meaning'],
  ['what does 999 mean', ['does 999 mean', 'does 999'], 'angel_numbers', 'meaning', '解读页', 'D1', '/questions/angel-numbers/999-meaning'],
  ['what does 1212 mean', ['does 1212 mean', 'does 1212'], 'angel_numbers', 'meaning', '解读页', 'D1', '/questions/angel-numbers/1212-meaning'],
  ['what does 1010 mean', ['does 1010 mean', 'does 1010'], 'angel_numbers', 'meaning', '解读页', 'D1', '/questions/angel-numbers/1010-meaning'],
  ['what does 1234 mean', ['does 1234 mean', 'does 1234'], 'angel_numbers', 'meaning', '解读页', 'D1', '/questions/angel-numbers/1234-meaning'],
  ['what does 111 mean', ['does 111 mean', 'does 111'], 'angel_numbers', 'meaning', '解读页', 'D1', '/questions/angel-numbers/111-meaning'],
  ['what does 2222 mean', ['does 2222 mean', 'does 2222'], 'angel_numbers', 'meaning', '解读页', 'D1', '/questions/angel-numbers/2222-meaning'],
  ['angel numbers meaning', ['angel numbers'], 'angel_numbers', 'meaning', '工具页', 'D1', '/questions/angel-numbers/angel-numbers-meaning'],
  ['why do i keep seeing 1111', ['keep seeing 1111'], 'angel_numbers', 'wh', '解读页', 'D1', '/questions/angel-numbers/why-do-i-keep-seeing-1111'],
  ['why do i keep seeing repeating numbers', ['repeating numbers', 'keep seeing angel numbers'], 'angel_numbers', 'wh', '解读页', 'D1', '/questions/angel-numbers/why-do-i-keep-seeing-repeating-numbers'],
  ['what is my life path number', ['life path number'], 'angel_numbers', 'wh', '工具页', 'D1', '/questions/angel-numbers/life-path-number'],
  ['what is my angel number', ['my angel number', 'angel number'], 'angel_numbers', 'wh', '工具页', 'D1', '/questions/angel-numbers/what-is-my-angel-number'],

  /* ============ 5. TAROT (14) ============ */
  ['how to read tarot', ['how to read tarot'], 'tarot', 'how_to', '指南页', 'D1', '/guides/how-to-read-tarot'],
  ['how to do a tarot reading', ['how to do a tarot reading'], 'tarot', 'how_to', '指南页', 'D1', '/guides/how-to-do-a-tarot-reading'],
  ['tarot yes or no', ['tarot yes or no', 'tarot yes'], 'tarot', 'how_to', '工具页', 'D1', '/questions/tarot/tarot-yes-or-no'],
  ['does he love me tarot', ['does he love me tarot'], 'tarot', 'yes_no', '决策页', 'D3', '/questions/tarot/does-he-love-me-tarot'],
  ['is tarot accurate', ['is tarot accurate', 'is tarot real', 'is tarot reading'], 'tarot', 'yes_no', '概念页', 'D2', '/guides/is-tarot-accurate'],
  ['can tarot predict the future', ['tarot predict the future'], 'tarot', 'yes_no', '概念页', 'D2', '/questions/tarot/can-tarot-predict-the-future'],
  ['what does the death card mean', ['death card mean', 'what is the death card'], 'tarot', 'meaning', '解读页', 'D1', '/questions/tarot/death-card-meaning'],
  ['what does the tower card mean', ['tower card mean'], 'tarot', 'meaning', '解读页', 'D1', '/questions/tarot/tower-card-meaning'],
  ['what does the lovers card mean', ['lovers card mean'], 'tarot', 'meaning', '解读页', 'D1', '/questions/tarot/lovers-card-meaning'],
  ['what does the moon card mean', ['moon card mean'], 'tarot', 'meaning', '解读页', 'D1', '/questions/tarot/moon-card-meaning'],
  ['what does the star card mean', ['star card mean'], 'tarot', 'meaning', '解读页', 'D1', '/questions/tarot/star-card-meaning'],
  ['what does the high priestess mean', ['high priestess'], 'tarot', 'meaning', '解读页', 'D1', '/questions/tarot/high-priestess-meaning'],
  ['how to cleanse tarot cards', ['cleanse tarot cards'], 'tarot', 'how_to', '指南页', 'D2', '/guides/how-to-cleanse-tarot-cards'],
  ['what is my tarot birth card', ['tarot birth card'], 'tarot', 'wh', '工具页', 'D1', '/questions/tarot/tarot-birth-card'],

  /* ============ 6. ASTROLOGY (18) ============ */
  ['what is my rising sign', ['my rising sign', 'rising sign'], 'astrology', 'wh', '工具页', 'D1', '/questions/astrology/what-is-my-rising-sign'],
  ['what is my moon sign', ['my moon sign', 'moon sign meaning'], 'astrology', 'wh', '工具页', 'D1', '/questions/astrology/what-is-my-moon-sign'],
  ['what is my sun sign', ['my sun sign'], 'astrology', 'wh', '工具页', 'D1', '/questions/astrology/what-is-my-sun-sign'],
  ['what is my big three', ['big three'], 'astrology', 'wh', '工具页', 'D1', '/questions/astrology/what-is-my-big-three'],
  ['how to read my birth chart', ['read my birth chart', 'read chart in astrology', 'chart your birth chart'], 'astrology', 'how_to', '指南页', 'D1', '/guides/how-to-read-your-birth-chart'],
  ['what does my birth chart mean', ['birth chart mean'], 'astrology', 'meaning', '指南页', 'D1', '/questions/astrology/what-does-my-birth-chart-mean'],
  ['what does mercury retrograde mean', ['mercury retrograde'], 'astrology', 'meaning', '解读页', 'D1', '/questions/astrology/mercury-retrograde-meaning'],
  ['what is my venus sign', ['my venus sign', 'venus sign'], 'astrology', 'wh', '工具页', 'D1', '/questions/astrology/what-is-my-venus-sign'],
  ['what is my north node', ['my north node', 'north node'], 'astrology', 'wh', '解读页', 'D1', '/questions/astrology/what-is-my-north-node'],
  ['what is my saturn return', ['saturn return'], 'astrology', 'wh', '解读页', 'D1', '/questions/astrology/what-is-my-saturn-return'],
  ['what is a stellium', ['stellium'], 'astrology', 'wh', '概念页', 'D1', '/questions/astrology/what-is-a-stellium'],
  ['what is my chiron', ['my chiron', 'chiron'], 'astrology', 'wh', '解读页', 'D1', '/questions/astrology/what-is-my-chiron'],
  ['when is the next mercury retrograde', ['mercury retrograde 2026', 'mercury retrograde'], 'astrology', 'wh', '解读页', 'D1', '/questions/astrology/mercury-retrograde-dates'],
  ['zodiac compatibility', ['zodiac compatibility'], 'astrology', 'wh', '工具页', 'D1', '/questions/astrology/zodiac-compatibility'],
  ['what sign is compatible with me', ['sign is compatible', 'compatible with me'], 'astrology', 'wh', '工具页', 'D1', '/questions/astrology/what-sign-is-compatible-with-me'],
  ['is astrology real', ['is astrology real', 'astrology real'], 'astrology', 'yes_no', '概念页', 'D2', '/guides/is-astrology-real'],
  ['what is my seventh house', ['seventh house', '7th house'], 'astrology', 'wh', '解读页', 'D1', '/questions/astrology/seventh-house-meaning'],
  ['what does my moon sign mean', ['moon sign mean'], 'astrology', 'meaning', '解读页', 'D1', '/questions/astrology/moon-sign-meaning'],
  /* ============ 7. PSYCHIC ABILITIES & INTUITION (14) ============ */
  ['am i psychic', ['am i psychic', 'i am psychic'], 'psychic_abilities', 'yes_no', '工具页', 'D2', '/questions/spiritual-growth/am-i-psychic'],
  ['am i clairvoyant', ['clairvoyant'], 'psychic_abilities', 'yes_no', '工具页', 'D2', '/questions/spiritual-growth/am-i-clairvoyant'],
  ['am i an empath', ['am i an empath', 'empath or'], 'psychic_abilities', 'yes_no', '工具页', 'D2', '/questions/spiritual-growth/am-i-an-empath'],
  ['am i an intuitive', ['am i an intuitive', 'intuitive empath'], 'psychic_abilities', 'yes_no', '工具页', 'D2', '/questions/spiritual-growth/am-i-an-intuitive'],
  ['signs you are psychic', ['signs you are psychic', 'spiritually gifted'], 'psychic_abilities', 'signs', '清单页', 'D1', '/questions/spiritual-growth/signs-you-are-psychic'],
  ['how to open third eye', ['open third eye', 'third eye'], 'psychic_abilities', 'how_to', '指南页', 'D2', '/guides/how-to-open-your-third-eye'],
  ['signs your third eye is opening', ['third eye is open', 'third eye opening'], 'psychic_abilities', 'signs', '清单页', 'D1', '/questions/spiritual-growth/third-eye-opening-signs'],
  ['how to develop psychic abilities', ['develop psychic abilities', 'psychic abilities'], 'psychic_abilities', 'how_to', '指南页', 'D2', '/guides/how-to-develop-psychic-abilities'],
  ['how to trust your intuition', ['trust your intuition', 'strengthen intuition', 'intuition'], 'psychic_abilities', 'how_to', '指南页', 'D2', '/guides/how-to-trust-your-intuition'],
  ['what is my psychic ability', ['my psychic ability', 'psychic ability'], 'psychic_abilities', 'wh', '工具页', 'D1', '/questions/spiritual-growth/what-is-my-psychic-ability'],
  ['what is my spiritual gift', ['spiritual gift'], 'psychic_abilities', 'wh', '工具页', 'D1', '/questions/spiritual-growth/what-is-my-spiritual-gift'],
  ['what is clairsentience', ['clairsentience'], 'psychic_abilities', 'wh', '概念页', 'D1', '/guides/clairsentience-explained'],
  ['how to find your spirit guide', ['spirit guide'], 'psychic_abilities', 'how_to', '指南页', 'D2', '/guides/how-to-find-your-spirit-guide'],
  ['what is the akashic records', ['akashic'], 'psychic_abilities', 'wh', '概念页', 'D2', '/guides/akashic-records-explained'],

  /* ============ 8. MANIFESTATION (14) ============ */
  ['how to manifest', ['how to manifest'], 'manifestation', 'how_to', '指南页', 'D2', '/guides/how-to-manifest'],
  ['how to manifest money', ['manifest money', 'manifest more money', 'manifest wealth'], 'manifestation', 'how_to', '指南页', 'D2', '/guides/how-to-manifest-money'],
  ['how to manifest love', ['manifest love'], 'manifestation', 'how_to', '指南页', 'D2', '/guides/how-to-manifest-love'],
  ['how to manifest a specific person', ['manifest a specific person', 'manifest someone', 'manifest him'], 'manifestation', 'how_to', '指南页', 'D3', '/guides/how-to-manifest-a-specific-person'],
  ['does manifestation work', ['manifestation work'], 'manifestation', 'yes_no', '概念页', 'D2', '/guides/does-manifestation-work'],
  ['369 method', ['369 method', '369'], 'manifestation', 'how_to', '指南页', 'D1', '/guides/369-manifestation-method'],
  ['what is the 555 method', ['555 method'], 'manifestation', 'wh', '指南页', 'D1', '/guides/555-manifestation-method'],
  ['scripting manifestation', ['scripting'], 'manifestation', 'how_to', '指南页', 'D1', '/guides/scripting-manifestation'],
  ['what is the law of assumption', ['law of assumption'], 'manifestation', 'wh', '概念页', 'D1', '/guides/law-of-assumption'],
  ['what is shadow work', ['shadow work'], 'manifestation', 'wh', '指南页', 'D1', '/guides/what-is-shadow-work'],
  ['how to do shadow work', ['do shadow work'], 'manifestation', 'how_to', '指南页', 'D1', '/guides/how-to-do-shadow-work'],
  ['how to raise your vibration', ['raise your vibration', 'vibration'], 'manifestation', 'how_to', '指南页', 'D1', '/guides/how-to-raise-your-vibration'],
  ['why is my manifestation not working', ['manifestation not working', 'manifestation is not working'], 'manifestation', 'wh', '指南页', 'D3', '/guides/why-your-manifestation-is-not-working'],
  ['how long does manifestation take', ['how long does manifestation take'], 'manifestation', 'wh', '概念页', 'D2', '/guides/how-long-manifestation-takes'],

  /* ============ 9. SPIRITUAL AWAKENING (10) ============ */
  ['what is a spiritual awakening', ['spiritual awakening'], 'spiritual_awakening', 'wh', '概念页', 'D1', '/guides/what-is-a-spiritual-awakening'],
  ['signs of spiritual awakening', ['signs of spiritual awakening', 'signs of a spiritual awakening'], 'spiritual_awakening', 'signs', '清单页', 'D1', '/questions/spiritual-growth/signs-of-spiritual-awakening'],
  ['spiritual awakening symptoms', ['awakening symptoms', 'symptoms of awakening'], 'spiritual_awakening', 'signs', '清单页', 'D1', '/questions/spiritual-growth/spiritual-awakening-symptoms'],
  ['am i spiritually awakening', ['spiritually awakening', 'spiritually awakened'], 'spiritual_awakening', 'yes_no', '工具页', 'D2', '/questions/spiritual-growth/am-i-spiritually-awakening'],
  ['dark night of the soul', ['dark night of the soul'], 'spiritual_awakening', 'wh', '概念页', 'D2', '/guides/dark-night-of-the-soul'],
  ['spiritual awakening stages', ['spiritual awakening stages', 'awakening stages'], 'spiritual_awakening', 'wh', '概念页', 'D1', '/guides/spiritual-awakening-stages'],
  ['signs of kundalini awakening', ['kundalini'], 'spiritual_awakening', 'signs', '指南页', 'D2', '/guides/kundalini-awakening-signs'],
  ['what is my spirit animal', ['spirit animal'], 'spiritual_awakening', 'wh', '工具页', 'D1', '/questions/spiritual-growth/what-is-my-spirit-animal'],
  ['waking up at 3am spiritual meaning', ['3am', '3 am'], 'spiritual_awakening', 'meaning', '解读页', 'D1', '/questions/spiritual-growth/waking-up-at-3am-meaning'],
  ['what is my aura color', ['aura color', 'aura'], 'spiritual_awakening', 'wh', '工具页', 'D1', '/questions/spiritual-growth/what-is-my-aura-color'],

  /* ============ 10. PROTECTION & CLEANSING (9) ============ */
  ['am i cursed', ['am i cursed', 'have i been cursed'], 'protection_energy', 'yes_no', '决策页', 'D3', '/questions/spiritual-growth/am-i-cursed'],
  ['how to break a curse', ['break a curse', 'remove a curse'], 'protection_energy', 'how_to', '指南页', 'D3', '/guides/how-to-break-a-curse'],
  ['what is the evil eye', ['evil eye'], 'protection_energy', 'wh', '概念页', 'D1', '/guides/evil-eye-meaning'],
  ['what is a hex', ['a hex'], 'protection_energy', 'wh', '概念页', 'D2', '/guides/hex-vs-curse'],
  ['how to cleanse negative energy', ['cleanse negative energy', 'cleanse your space', 'cleanse negative energy from'], 'protection_energy', 'how_to', '指南页', 'D2', '/guides/how-to-cleanse-negative-energy'],
  ['how to get rid of negative energy', ['get rid of negative energy'], 'protection_energy', 'how_to', '指南页', 'D2', '/guides/how-to-cleanse-negative-energy'],
  ['how to protect yourself from negative energy', ['protect yourself from negative energy', 'protect your energy'], 'protection_energy', 'how_to', '指南页', 'D2', '/guides/protecting-your-energy'],
  ['how to cleanse your aura', ['cleanse your aura'], 'protection_energy', 'how_to', '指南页', 'D2', '/guides/how-to-cleanse-your-aura'],
  ['signs of negative energy around you', ['negative energy around', 'bad energy in house', 'negative energy in house'], 'protection_energy', 'signs', '清单页', 'D1', '/questions/spiritual-growth/signs-of-negative-energy'],

  /* ============ 11. SIGNS & SYNCHRONICITY (8) ============ */
  ['what does it mean when you see a cardinal', ['cardinal'], 'signs_synchronicity', 'meaning', '解读页', 'D1', '/questions/signs/cardinal-meaning'],
  ['what does it mean when you see a feather', ['feather'], 'signs_synchronicity', 'meaning', '解读页', 'D1', '/questions/signs/feather-meaning'],
  ['what does it mean when you see a deer', ['deer'], 'signs_synchronicity', 'meaning', '解读页', 'D1', '/questions/signs/deer-meaning'],
  ['what does it mean when you see a hawk', ['hawk'], 'signs_synchronicity', 'meaning', '解读页', 'D1', '/questions/signs/hawk-meaning'],
  ['what does it mean when you see an owl', ['owl'], 'signs_synchronicity', 'meaning', '解读页', 'D1', '/questions/signs/owl-meaning'],
  ['butterfly meaning spiritual', ['butterfly'], 'signs_synchronicity', 'meaning', '解读页', 'D1', '/questions/signs/butterfly-meaning'],
  ['hummingbird meaning spiritual', ['hummingbird'], 'signs_synchronicity', 'meaning', '解读页', 'D1', '/questions/signs/hummingbird-meaning'],
  ['what are synchronicities', ['synchronicit', 'sign from the universe', 'signs from the universe'], 'signs_synchronicity', 'wh', '概念页', 'D1', '/guides/what-are-synchronicities'],

  /* ============ 12. CRYSTALS, MOON & RITUAL (9) ============ */
  ['full moon ritual', ['full moon ritual', 'full moon ceremony'], 'crystals_rituals', 'how_to', '指南页', 'D1', '/guides/full-moon-ritual'],
  ['what to do on a full moon', ['what to do on a full moon'], 'crystals_rituals', 'how_to', '指南页', 'D1', '/guides/full-moon-ritual'],
  ['new moon ritual', ['new moon ritual'], 'crystals_rituals', 'how_to', '指南页', 'D1', '/guides/new-moon-ritual'],
  ['what does the full moon mean', ['full moon mean', 'does a full moon'], 'crystals_rituals', 'meaning', '解读页', 'D1', '/questions/crystals-rituals/full-moon-meaning'],
  ['moon phases meaning', ['moon phase'], 'crystals_rituals', 'meaning', '解读页', 'D1', '/questions/crystals-rituals/moon-phases-meaning'],
  ['how to cleanse crystals', ['cleanse crystals', 'cleanse a crystal'], 'crystals_rituals', 'how_to', '指南页', 'D2', '/guides/how-to-cleanse-crystals'],
  ['crystals for anxiety', ['crystals for anxiety'], 'crystals_rituals', 'wh', '清单页', 'D1', '/guides/crystals-for-anxiety'],
  ['crystals for love', ['crystals for love'], 'crystals_rituals', 'wh', '清单页', 'D1', '/guides/crystals-for-love'],
  ['what crystal is for protection', ['crystal is for protection', 'crystals for protection'], 'crystals_rituals', 'wh', '清单页', 'D1', '/guides/crystals-for-protection'],

  /* ============ 13. CHAKRAS & ENERGY (7) ============ */
  ['what are chakras', ['what are chakras', 'chakra'], 'chakras_energy', 'wh', '概念页', 'D1', '/guides/what-are-chakras'],
  ['how to unblock chakras', ['unblock chakras', 'unblock heart chakra', 'unblock throat chakra'], 'chakras_energy', 'how_to', '指南页', 'D2', '/guides/how-to-unblock-chakras'],
  ['which chakra is blocked', ['chakra is blocked', 'blocked chakra', 'chakra test'], 'chakras_energy', 'wh', '工具页', 'D1', '/quiz/chakra-test'],
  ['signs of blocked chakras', ['blocked chakra signs', 'chakra blocked'], 'chakras_energy', 'signs', '清单页', 'D1', '/questions/spiritual-growth/blocked-chakra-signs'],
  ['what is reiki', ['reiki'], 'chakras_energy', 'wh', '概念页', 'D2', '/guides/what-is-reiki'],
  ['what is the third eye chakra', ['third eye chakra'], 'chakras_energy', 'wh', '概念页', 'D1', '/guides/third-eye-chakra'],
  ['what is energy healing', ['energy healing'], 'chakras_energy', 'wh', '概念页', 'D2', '/guides/energy-healing-explained'],
  ['how to balance chakras', ['balance chakras', 'balance your chakras'], 'chakras_energy', 'how_to', '指南页', 'D2', '/guides/how-to-balance-your-chakras'],

  /* ============ 14. PAST LIVES & KARMA (6) ============ */
  ['past life regression', ['past life regression'], 'past_lives_karma', 'wh', '概念页', 'D2', '/guides/past-life-regression'],
  ['how to know my past life', ['know my past life', 'past life'], 'past_lives_karma', 'how_to', '指南页', 'D1', '/questions/spiritual-growth/how-to-know-your-past-life'],
  ['past life signs', ['past life signs', 'signs of a past life'], 'past_lives_karma', 'signs', '清单页', 'D1', '/questions/spiritual-growth/past-life-signs'],
  ['what is karma', ['what is karma', 'karma'], 'past_lives_karma', 'wh', '概念页', 'D1', '/guides/what-is-karma'],
  ['how to clear karma', ['clear karma'], 'past_lives_karma', 'how_to', '指南页', 'D2', '/guides/how-to-clear-karma'],
  ['what is a soul contract', ['soul contract'], 'past_lives_karma', 'wh', '概念页', 'D1', '/guides/soul-contracts'],

  /* ============ 15. GRIEF & AFTERLIFE (9) ============ */
  ['signs from deceased loved ones', ['deceased loved one', 'passed loved one', 'loved one is still with'], 'grief_afterlife', 'signs', '清单页', 'D2', '/questions/loss-closure/signs-from-deceased-loved-ones'],
  ['can mediums talk to the dead', ['mediums talk to the dead', 'talk to the dead', 'connect with the dead'], 'grief_afterlife', 'yes_no', '概念页', 'D2', '/guides/can-mediums-talk-to-the-dead'],
  ['are mediums real', ['mediums real', 'know if a medium is real'], 'grief_afterlife', 'yes_no', '概念页', 'D3', '/guides/how-to-know-if-a-medium-is-real'],
  ['is my loved one watching over me', ['watching over me', 'watching over you'], 'grief_afterlife', 'yes_no', '决策页', 'D2', '/questions/loss-closure/is-my-loved-one-watching-over-me'],
  ['what happens after death spiritually', ['after death'], 'grief_afterlife', 'wh', '概念页', 'D1', '/questions/loss-closure/what-happens-after-death'],
  ['how to connect with a passed loved one', ['connect with a passed', 'connect with my loved one', 'contact a loved one'], 'grief_afterlife', 'how_to', '指南页', 'D2', '/guides/connecting-with-a-passed-loved-one'],
  ['am i being haunted', ['am i being haunted', 'haunted'], 'grief_afterlife', 'yes_no', '决策页', 'D2', '/questions/loss-closure/am-i-being-haunted'],
  ['signs of a spirit in your house', ['spirit in your house', 'spirit in my house'], 'grief_afterlife', 'signs', '清单页', 'D1', '/questions/loss-closure/signs-of-a-spirit-in-your-house'],

  /* ============ 16. MONEY, CAREER & PURPOSE (10) ============ */
  ['what is my life purpose', ['life purpose', 'my purpose in life', 'my purpose'], 'money_career', 'wh', '决策页', 'D2', '/questions/life-direction/what-is-my-life-purpose'],
  ['what is my soul purpose', ['soul purpose'], 'money_career', 'wh', '决策页', 'D2', '/questions/life-direction/what-is-my-soul-purpose'],
  ['what is my career path', ['career path'], 'money_career', 'wh', '决策页', 'D2', '/questions/career-work/what-is-my-career-path'],
  ['is this job right for me', ['job right for me', 'right career for me'], 'money_career', 'yes_no', '决策页', 'D3', '/questions/career-work/is-this-job-right-for-me'],
  ['should i quit my job', ['quit my job'], 'money_career', 'yes_no', '决策页', 'D3', '/questions/career-work/should-i-quit-my-job'],
  ['will i get the job', ['get the job'], 'money_career', 'yes_no', '决策页', 'D3', '/questions/career-work/will-i-get-the-job'],
  ['will i be successful', ['be successful'], 'money_career', 'yes_no', '决策页', 'D2', '/questions/career-work/will-i-be-successful'],
  ['will i be rich', ['be rich'], 'money_career', 'yes_no', '决策页', 'D2', '/questions/money-wealth/will-i-be-rich'],
  ['what is my destiny', ['my destiny', 'destiny'], 'money_career', 'wh', '决策页', 'D2', '/questions/life-direction/what-is-my-destiny'],
  ['what does my future hold', ['future hold', 'does the future hold'], 'money_career', 'wh', '决策页', 'D2', '/questions/life-direction/what-does-my-future-hold'],
];
